#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cstring>
#include <cmath>
#include <cstdlib>
#include <ctime>
#define x first
#define y second
#define LL long long
#define mp make_pair
using namespace std;

typedef pair<int, int> per;
typedef vector<int>::iterator it;
typedef multiset<int>::iterator is;

multiset<int> mici,mari,m[2];

int smici,smari;

struct ICPCBalloons {
	int minRepaintings(vector <int> bc, string bs, vector <int> ma) {
		int rez=(1<<30);
		for(int i=0; i<bc.size(); ++i) {
			if(bs[i]=='M') {
				mici.insert(bc[i]);
				smici+=bc[i];
			}
			else {
				mari.insert(bc[i]);
				smari+=bc[i];
			}
		}
		mici.insert(0); mari.insert(0);
		sort(ma.rbegin(),ma.rend());
		int lim=(1<<ma.size());
		for(int s=0; s<lim; ++s) {
			int ct=0;
			m[1]=mici; m[0]=mari;
			int smc=0,smac=0;
			for(int j=0; j<ma.size(); ++j) {
				if(s&(1<<j)) smc+=ma[j];
				else smac+=ma[j];
			}
			if(smc>smici || smac>smari) continue;
			m[0].insert(0); m[1].insert(0);
			for(int j=0; j<ma.size(); ++j) {
				int bit=(s&(1<<j));
				is p=m[bit].lower_bound(ma[j]);
				for(;p!=m[bit].end();--p);// if(p!=m[bit].end()) break;
				if(*p<ma[j]) ct+=ma[j]-*p;
				m[bit].erase(p);
				m[bit].insert(0);
			}
			rez=min(rez,ct);
		}
		if(rez==(1<<30))return -1;
		return rez;
	}
};


//Powered by [KawigiEdit] 2.0!



// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <int> p0, string p1, vector <int> p2, bool hasAnswer, int p3) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << "\"" << p1 << "\"" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p2[i];
	}
	cout << "}";
	cout << "]" << endl;
	ICPCBalloons *obj;
	int answer;
	obj = new ICPCBalloons();
	clock_t startTime = clock();
	answer = obj->minRepaintings(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p3 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p3;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <int> p0;
	string p1;
	vector <int> p2;
	int p3;
	
	{
	// ----- test 0 -----
	int t0[] = {100};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "L";
	int t2[] = {1,2,3,4,5};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 10;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	int t0[] = {100};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "M";
	int t2[] = {10,20,30,40,50};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = -1;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	int t0[] = {5,6,1,5,6,1,5,6,1};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "MLMMLMMLM";
	int t2[] = {7,7,4,4,7,7};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 6;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	int t0[] = {100,100};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "ML";
	int t2[] = {50,51,51};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = -1;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	int t0[] = {8,5,1,4,1,1,3,1,3,3,5,4,5,6,9};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "MMMLLLMMLLMLMLM";
	int t2[] = {3,5,3,3,5,6,4,6,4,2,3,7,1,5,2};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 5;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	int t0[] = {1,18,4,7,19,7,7,1,4,8,10,5,14,13,8,22,6,3,13,5,3,4,2,1,3,15,19,4,5,9,4,11,2,7,12,20,11,26,22,7,2,10,9,20,13,20,2,9,11,9};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "LLMLLLLMLLLLLLLLLLLLMLLLLLLLLLLMMLMLLLMLLLLLLLLMLL";
	int t2[] = {44,59,29,53,16,23,13,14,29,42,13,15,66,4,47};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 210;
	all_right = KawigiEdit_RunTest(5, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
